### ISSUE TITLE
Looking for a maintainer

### ISSUE THREAD

**Issue by anachronistic** [anachronistic/apns#35]
I don't have the bandwidth to keep up with Apple life these days, so I'd like to pass this to someone else to maintain. Otherwise I'll drop an "unmaintained" badge on the README so the status is clear.

**Comment by Coccodrillo** [comment]
Hey, I am using this in a production setup with 6 figure users on board, so I am going to maintain this one way or another (as a fork). If you're still up for it, I am happy to take this over.

**Comment by anachronistic** [comment]
Sure thing! Much obliged :)
